### ISSUE TITLE
scripts refused to be insecure on https

### ISSUE THREAD

**Issue by urbient** [tunguskha/wonder-cms-material-theme#2]
i run my own server with dockerized apache behind a nginx proxie served by a automated letsencrypt instance . the browser does not load the blue and red bars as they come from unsecure sources . 

edit : sorry i thought it is only your theme , but it seems that all are affected .
its a cross protocol problem inside wondercms , mixing https and loading from http only

thank you

**Comment by tunguskha** [comment]
Hello, thank you for your issue. But this error does not come from the theme. Try opening an issue directly on the WonderCMS repo or go to the forum, you might find a solution.
